version: '3.9'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
    command: pnpm dev
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - ENV=dev
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: scriptum
      POSTGRES_PASSWORD: scriptum
      POSTGRES_DB: scriptum
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
   
        n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin
    volumes:
      - n8n_data:/home/node/.n8n

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./devops/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana

  loki:
    image: grafana/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
volumes:
  db_data:
  n8n_data:
  grafana_data:

volumes:
  db_data:
